### ISSUE TITLE
Github Oauth Error

### ISSUE THREAD

**Issue by ChrisLally** [JonKimbel/SheetsToJson#1]
When attempting to authorize github, this error is triggered after entering credentials 

Exception: Request to https://github.com/login/oauth/access_token failed because the URL has not been whitelisted in the script manifest. (line 510, file "Service")

**Comment by JonKimbel** [comment]
I could repro, this should be fixed by [2b92b29e261bc1f22fc7b1503dae5cb4ed68d6bf](https://github.com/JonKimbel/SheetsToJson/commit/2b92b29e261bc1f22fc7b1503dae5cb4ed68d6bf) -- after pushing that to the sheets addon store I can no longer repro.
